spring.datasource.url=jdbc:postgresql://${RT_HOST}/${RT_NAME}
spring.datasource.username=${RT_USER}
spring.datasource.password=${RT_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialect.HSQLDialect

spring.jpa.hibernate.ddl-auto=update